version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
  web:
    build: .
    command: poetry run python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/app
    ports:
      - "8000:8000"
    depends_on:
      - db
