version: "3"

services:
  db:
    image: postgres:12
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  web:
    build: .
    command: poetry run python3 manage.py runserver 0.0.0.0:8000 --settings config.settings.local
    volumes:
      - .:/opt/app
    ports:
      - "8000:8000"
    depends_on:
      - db
