version: "3"

services:
  db:
    image: postgres:12
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  web:
    build: .
    command: >
      poetry run
      uvicorn config.asgi:application
      --host 0.0.0.0 --reload
    volumes:
      - .:/opt/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
