version: "3"

services:
  db:
    image: postgres:12
    ports:
      - "5432"
    env_file:
      - envs/.env.db.local
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: >
      uvicorn config.asgi:application
      --host 0.0.0.0 --reload
    volumes:
      - .:/opt/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - envs/.env.local
